-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./TelegramAuthorization.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE telegram_users (
  id INT NOT NULL,
  tg_id INT NOT NULL,
  PRIMARY KEY(id)
);

CREATE UNIQUE INDEX id ON telegram_users (id);
