-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./TelegramAuthorization.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/telegram_users (
  id INTEGER UNSIGNED NOT NULL,
  tg_id INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id)
);

CREATE UNIQUE INDEX id ON /*_*/telegram_users (id);
