-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./TelegramAuthorization.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/telegram_users (
  id INT UNSIGNED NOT NULL,
  tg_id INT UNSIGNED NOT NULL,
  UNIQUE INDEX id (id),
  PRIMARY KEY(id)
) /*$wgDBTableOptions*/;
